import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GeistSans } from "geist/font/sans";

import "./globals.css";
import { Navbar } from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "CHONGLAND",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang="en"
			className={`${GeistSans.variable} text-black bg-white dark:text-white dark:bg-[#111010]`}
		>
			<body className={inter.className}>
				<main className="container mx-auto flex flex-col px-2 md:px-0">
					<Navbar />
					{children}
				</main>
			</body>
		</html>
	);
}
