import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';

import './globals.css';
import { Navbar } from '@/components/Navbar';
import SectionContainer from '@/components/SectionContainer';

export const metadata: Metadata = {
	title: 'CHONGLAND',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang='en'
			className={`${GeistSans.variable} text-black bg-white dark:text-white dark:bg-[#111010]`}
		>
			<body>
				<SectionContainer>
					<Navbar />
					<main className='mx-auto'>{children}</main>
				</SectionContainer>
			</body>
		</html>
	);
}
